import { PDFDocument as PDFLibDoc, rgb, StandardFonts, degrees } from 'pdf-lib';
import { PDFDocument, PDFPage } from '../types/pdf';

// Helper to convert hex color to RGB 0-1
function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const cleanHex = hex.replace('#', '');
  if (cleanHex.length === 3) {
    const r = parseInt(cleanHex[0] + cleanHex[0], 16) / 255;
    const g = parseInt(cleanHex[1] + cleanHex[1], 16) / 255;
    const b = parseInt(cleanHex[2] + cleanHex[2], 16) / 255;
    return { r, g, b };
  }
  const r = parseInt(cleanHex.substring(0, 2), 16) / 255;
  const g = parseInt(cleanHex.substring(2, 4), 16) / 255;
  const b = parseInt(cleanHex.substring(4, 6), 16) / 255;
  return {
    r: isNaN(r) ? 0 : r,
    g: isNaN(g) ? 0 : g,
    b: isNaN(b) ? 0 : b,
  };
}

export async function exportToPDFBlob(doc: PDFDocument): Promise<Blob> {
  const pdfDoc = await PDFLibDoc.create();

  // Embed standard fonts
  const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const timesFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const timesBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);
  const courierFont = await pdfDoc.embedFont(StandardFonts.Courier);
  const courierBold = await pdfDoc.embedFont(StandardFonts.CourierBold);

  // Set document metadata
  pdfDoc.setTitle(doc.title);
  pdfDoc.setAuthor(doc.author);
  pdfDoc.setSubject(doc.subject || 'Generated by WinPDF Studio Pro');
  pdfDoc.setProducer('WinPDF Studio Pro (Windows PDF Suite)');
  pdfDoc.setCreationDate(new Date(doc.createdAt));
  pdfDoc.setModificationDate(new Date(doc.modifiedAt));

  for (const page of doc.pages) {
    // Standard A4: 595.28 x 841.89 points
    const pdfPage = pdfDoc.addPage([595.28, 841.89]);
    const { width, height } = pdfPage.getSize();

    // 1. Embed background image if page is scanned/has background
    if (page.backgroundImage && page.backgroundImage.startsWith('data:image')) {
      try {
        let image;
        if (page.backgroundImage.includes('image/png')) {
          image = await pdfDoc.embedPng(page.backgroundImage);
        } else {
          image = await pdfDoc.embedJpg(page.backgroundImage);
        }
        pdfPage.drawImage(image, {
          x: 0,
          y: 0,
          width,
          height,
        });
      } catch (err) {
        console.warn('Failed to embed background image in PDF export:', err);
      }
    }

    // 2. Render Text Blocks directly in document layout
    for (const block of page.textBlocks) {
      // PDF coordinate system origin is bottom-left, our canvas is top-left
      const blockWidth = (block.width / 100) * width;
      const blockHeight = (block.height / 100) * height;
      const blockX = (block.x / 100) * width;
      const blockYTop = (block.y / 100) * height;
      const blockY = height - blockYTop - (block.fontSize * 1.2);

      // Select font
      let font = helveticaFont;
      const isBold = block.fontWeight === 'bold' || block.fontWeight === '600';
      if (block.fontFamily.toLowerCase().includes('times') || block.fontFamily.toLowerCase().includes('georgia')) {
        font = isBold ? timesBold : timesFont;
      } else if (block.fontFamily.toLowerCase().includes('courier')) {
        font = isBold ? courierBold : courierFont;
      } else {
        font = isBold ? helveticaBold : helveticaFont;
      }

      const { r, g, b } = hexToRgb(block.color);
      const lines = block.text.split('\n');
      const fontSize = Math.max(7, Math.min(block.fontSize, 36));
      const lineStep = fontSize * (block.lineHeight || 1.3);

      lines.forEach((lineText, lineIdx) => {
        if (!lineText.trim()) return;
        const currentY = blockY - (lineIdx * lineStep);
        if (currentY > 0 && currentY < height) {
          try {
            pdfPage.drawText(lineText, {
              x: blockX,
              y: currentY,
              size: fontSize,
              font: font,
              color: rgb(r, g, b),
              maxWidth: blockWidth,
            });
          } catch (e) {
            // In case of unsupported unicode glyphs in standard font
            console.warn('drawText warning:', e);
          }
        }
      });
    }

    // 3. Render Annotations
    for (const ann of page.annotations) {
      const annX = (ann.x / 100) * width;
      const annYTop = (ann.y / 100) * height;
      const annWidth = (ann.width / 100) * width;
      const annHeight = (ann.height / 100) * height;
      const annY = height - annYTop - annHeight;

      if (ann.type === 'highlight') {
        const { r, g, b } = hexToRgb(ann.color || '#fef08a');
        pdfPage.drawRectangle({
          x: annX,
          y: annY,
          width: annWidth,
          height: annHeight,
          color: rgb(r, g, b),
          opacity: ann.opacity || 0.45,
        });
      } else if (ann.type === 'redaction') {
        // Redaction is permanent black out
        pdfPage.drawRectangle({
          x: annX,
          y: annY,
          width: annWidth,
          height: annHeight,
          color: rgb(0, 0, 0),
          opacity: 1,
        });
      } else if (ann.type === 'shape') {
        const { r, g, b } = hexToRgb(ann.color || '#2563eb');
        if (ann.shapeType === 'ellipse') {
          pdfPage.drawEllipse({
            x: annX + annWidth / 2,
            y: annY + annHeight / 2,
            xScale: annWidth / 2,
            yScale: annHeight / 2,
            borderColor: rgb(r, g, b),
            borderWidth: ann.strokeWidth || 2,
            opacity: ann.opacity || 0.8,
          });
        } else {
          pdfPage.drawRectangle({
            x: annX,
            y: annY,
            width: annWidth,
            height: annHeight,
            borderColor: rgb(r, g, b),
            borderWidth: ann.strokeWidth || 2,
            opacity: ann.opacity || 0.8,
          });
        }
      } else if (ann.type === 'stamp') {
        const stampText = ann.stampType || 'APPROVED';
        const stampColor = ann.stampType === 'REJECTED' ? rgb(0.85, 0.1, 0.1) : rgb(0.1, 0.6, 0.2);
        pdfPage.drawRectangle({
          x: annX,
          y: annY,
          width: Math.max(annWidth, 120),
          height: Math.max(annHeight, 35),
          borderColor: stampColor,
          borderWidth: 2,
        });
        pdfPage.drawText(stampText, {
          x: annX + 10,
          y: annY + 10,
          size: 14,
          font: helveticaBold,
          color: stampColor,
        });
      } else if (ann.type === 'signature' && ann.signatureData) {
        if (ann.signatureData.startsWith('data:image')) {
          try {
            const sigImg = await pdfDoc.embedPng(ann.signatureData);
            pdfPage.drawImage(sigImg, {
              x: annX,
              y: annY,
              width: annWidth,
              height: annHeight,
            });
          } catch (e) {
            console.warn('Failed to embed signature image:', e);
          }
        } else {
          // Typed signature
          pdfPage.drawText(ann.signatureData, {
            x: annX + 5,
            y: annY + 5,
            size: 16,
            font: timesBold,
            color: rgb(0.08, 0.15, 0.4),
          });
        }
      }
    }

    // 4. Render Security Watermark if enabled
    if (doc.security.watermark.enabled && doc.security.watermark.text) {
      const wmText = doc.security.watermark.text;
      const { r, g, b } = hexToRgb(doc.security.watermark.color || '#94a3b8');
      pdfPage.drawText(wmText, {
        x: width * 0.15,
        y: height * 0.4,
        size: doc.security.watermark.fontSize || 42,
        font: helveticaBold,
        color: rgb(r, g, b),
        opacity: doc.security.watermark.opacity || 0.18,
        rotate: degrees(doc.security.watermark.rotation || -45),
      });
    }
  }

  const pdfBytes = await pdfDoc.save();
  return new Blob([pdfBytes.buffer as ArrayBuffer], { type: 'application/pdf' });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
